trigger:
  - main

pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - task: DownloadSecureFile@1
    name: authkey
    displayName: 'Download Service Account Key'
    inputs:
      secureFile: 'plated-field-319621-0ad41bf8702d.json'
      retryCount: '2'

  - script: echo $(authkey.secureFilePath)
    displayName: 'Deploy to CE'

  - script: gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
    displayName: 'Sign in to publisher SA'

  - script: gcloud beta compute ssh --zone "us-central1-a" "instance-2"  --project "plated-field-319621"
    displayName: 'Access VM'

  - script: sudo apt-get update
    displayName: 'Update package manager'

  - script: curl -sL \ https://deb.nodesource.com/setup_10.x \ | sudo -E bash -
    displayName: 'Install npm'

  - script: sudo apt-get install git nodejs
    displayName: 'Install Nodejs and Git'

  - script: sudo npm install
    displayName: 'Install language dependencies'

  - script: npm run start
    displayName: 'Boot application'
